// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldmvkyxbjfehdewogsia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbXZreXhiamZlaGRld29nc2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjkzMjcsImV4cCI6MjA2Mzg0NTMyN30.0-YW4AWgZX3S9m5fEiY6PM-BfqXTG444rEN_Pdchx2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);